apiVersion: apps/v1
kind: Deployment

metadata:
  name: mlops-face-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: mlops-face-app

  template:
    metadata:
      labels:
        app: mlops-face-app

    spec:
      containers:
      - name: mlops-face-app
        image: arpitsystems/mlops-face-app:latest

        ports:
        - containerPort: 5000